// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiKgCAb_A_7wl__yHVD5X3Xa38xLewMjk',
    appId: '1:367648060178:web:f56b1315319f821e4979cb',
    messagingSenderId: '367648060178',
    projectId: 'grocery-app-14eca',
    authDomain: 'grocery-app-14eca.firebaseapp.com',
    storageBucket: 'grocery-app-14eca.firebasestorage.app',
    measurementId: 'G-Y9EHMSGTVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWwVeC8ifTvOX3ChuXMCqNnjn75YdzVog',
    appId: '1:367648060178:android:8a5913edd4f2f63c4979cb',
    messagingSenderId: '367648060178',
    projectId: 'grocery-app-14eca',
    storageBucket: 'grocery-app-14eca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0MxRtlaYKuyXiQaIncqwfGWKNvVIHckc',
    appId: '1:367648060178:ios:0ac6d708ad38b93d4979cb',
    messagingSenderId: '367648060178',
    projectId: 'grocery-app-14eca',
    storageBucket: 'grocery-app-14eca.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0MxRtlaYKuyXiQaIncqwfGWKNvVIHckc',
    appId: '1:367648060178:ios:0ac6d708ad38b93d4979cb',
    messagingSenderId: '367648060178',
    projectId: 'grocery-app-14eca',
    storageBucket: 'grocery-app-14eca.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiKgCAb_A_7wl__yHVD5X3Xa38xLewMjk',
    appId: '1:367648060178:web:8fcf005c657dfdca4979cb',
    messagingSenderId: '367648060178',
    projectId: 'grocery-app-14eca',
    authDomain: 'grocery-app-14eca.firebaseapp.com',
    storageBucket: 'grocery-app-14eca.firebasestorage.app',
    measurementId: 'G-YGYT3VPQK1',
  );
}
