import 'package:flutter/material.dart';
import 'package:grocery_app/core/entites/product_entity.dart';

import '../models/category_model.dart';
import '../utils/app_images.dart';

class AppConstants {
  static const String productImageUrl =
      "https://m.media-amazon.com/images/I/61dV53UuRVS.__AC_SX300_SY300_QL70_FMwebp_.jpg";

  static List<Color> gridColors = [
    const Color(0xff53B175),
    const Color(0xffF8A44C),
    const Color(0xffF7A593),
    const Color(0xffD3B0E0),
    const Color(0xffFDE598),
    const Color(0xffB7DFF5),
  ];

  static List<CategoryModel> categoriesList = [
    CategoryModel(id: "Fruits", image: Assets.imagesCatFruits, name: "Fruits"),
    CategoryModel(
      id: "Vegetables",
      image: Assets.imagesCatVeg,
      name: "Vegetables",
    ),
    CategoryModel(id: "Herbs", image: Assets.imagesCatSpinach, name: "Herbs"),
    CategoryModel(id: "Nuts", image: Assets.imagesCatNuts, name: "Nuts"),
    CategoryModel(id: "Spices", image: Assets.imagesCatSpices, name: "Spices"),
    CategoryModel(id: "Grains", image: Assets.imagesCatGrains, name: "Grains"),
  ];
  // static List<Map<String, dynamic>> catInfo = [
  //   {'imgPath': Assets.imagesCatFruits, 'catText': 'Fruits'},
  //   {'imgPath': Assets.imagesCatVeg, 'catText': 'Vegetables'},
  //   {'imgPath': Assets.imagesCatSpinach, 'catText': 'Herbs'},
  //   {'imgPath': Assets.imagesCatNuts, 'catText': 'Nuts'},
  //   {'imgPath': Assets.imagesCatSpices, 'catText': 'Spices'},
  //   {'imgPath': Assets.imagesCatGrains, 'catText': 'Grains'},
  // ];

  static final List<String> offerImages = [
    'assets/images/offres/Offer1.jpg',
    'assets/images/offres/Offer2.jpg',
    'assets/images/offres/Offer3.jpg',
    'assets/images/offres/Offer4.jpg',
  ];
  static List<String> authImagesPaths = [
    'assets/images/landing/buy-on-laptop.jpg',
    'assets/images/landing/buy-through.png',
    'assets/images/landing/buyfood.jpg',
    'assets/images/landing/grocery-cart.jpg',
    'assets/images/landing/grocery-cart.jpg',
    'assets/images/landing/store.jpg',
    'assets/images/landing/vergtablebg.jpg',
  ];

  static final List<ProductEntity> productsList = [
    ProductEntity(
      productId: 'Apricot',
      name: 'Apricot',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      category: 'Fruits',
      isOnSale: true,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Avocado',
      name: 'Avocado',
      price: 0.88,
      salePrice: 0.5,
      imageUrl: 'https://i.ibb.co/9VKXw5L/Avocat.png',
      category: 'Fruits',
      isOnSale: false,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Black grapes',
      name: 'Black grapes',
      price: 1.22,
      salePrice: 0.7,
      imageUrl: 'https://i.ibb.co/c6w5zrC/Black-Grapes-PNG-Photos.png',
      category: 'Fruits',
      isOnSale: true,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Fresh_green_grape',
      name: 'Fresh green grape',
      price: 1.5,
      salePrice: 0.5,
      imageUrl: 'https://i.ibb.co/HKx2bsp/Fresh-green-grape.png',
      category: 'Fruits',
      isOnSale: true,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Green grape',
      name: 'Green grape',
      price: 0.99,
      salePrice: 0.4,
      imageUrl: 'https://i.ibb.co/bHKtc33/grape-green.png',
      category: 'Fruits',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Red apple',
      name: 'Red apple',
      price: 0.6,
      salePrice: 0.2,
      imageUrl: 'https://i.ibb.co/crwwSG2/red-apple.png',
      category: 'Fruits',
      isOnSale: true,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    // Vegi
    ProductEntity(
      productId: 'Carottes',
      name: 'Carottes',
      price: 0.99,
      salePrice: 0.5,
      imageUrl: 'https://i.ibb.co/TRbNL3c/Carottes.png',
      category: 'Vegetables',
      isOnSale: true,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Cauliflower',
      name: 'Cauliflower',
      price: 1.99,
      salePrice: 0.99,
      imageUrl: 'https://i.ibb.co/xGWf2rH/Cauliflower.png',
      category: 'Vegetables',
      isOnSale: false,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Cucumber',
      name: 'Cucumber',
      price: 0.99,
      salePrice: 0.5,
      imageUrl: 'https://i.ibb.co/kDL5GKg/cucumbers.png',
      category: 'Vegetables',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Jalape',
      name: 'Jalape',
      price: 1.99,
      salePrice: 0.89,
      imageUrl: 'https://i.ibb.co/Dtk1YP8/Jalape-o.png',
      category: 'Vegetables',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Long yam',
      name: 'Long yam',
      price: 2.99,
      salePrice: 1.59,
      imageUrl: 'https://i.ibb.co/V3MbcST/Long-yam.png',
      category: 'Vegetables',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Onions',
      name: 'Onions',
      price: 0.59,
      salePrice: 0.28,
      imageUrl: 'https://i.ibb.co/GFvm1Zd/Onions.png',
      category: 'Vegetables',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Plantain-flower',
      name: 'Plantain-flower',
      price: 0.99,
      salePrice: 0.389,
      imageUrl: 'https://i.ibb.co/RBdq0PD/Plantain-flower.png',
      category: 'Vegetables',
      isOnSale: false,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Potato',
      name: 'Potato',
      price: 0.99,
      salePrice: 0.59,
      imageUrl: 'https://i.ibb.co/wRgtW55/Potato.png',
      category: 'Vegetables',
      isOnSale: true,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Radish',
      name: 'Radish',
      price: 0.99,
      salePrice: 0.79,
      imageUrl: 'https://i.ibb.co/YcN4ZsD/Radish.png',
      category: 'Vegetables',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Red peppers',
      name: 'Red peppers',
      price: 0.99,
      salePrice: 0.57,
      imageUrl: 'https://i.ibb.co/JthGdkh/Red-peppers.png',
      category: 'Vegetables',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Squash',
      name: 'Squash',
      price: 3.99,
      salePrice: 2.99,
      imageUrl: 'https://i.ibb.co/p1V8sq9/Squash.png',
      category: 'Vegetables',
      isOnSale: true,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Tomatoes',
      name: 'Tomatoes',
      price: 0.99,
      salePrice: 0.39,
      imageUrl: 'https://i.ibb.co/PcP9xfK/Tomatoes.png',
      category: 'Vegetables',
      isOnSale: true,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    // Grains
    ProductEntity(
      productId: 'Corn-cobs',
      name: 'Corn-cobs',
      price: 0.29,
      salePrice: 0.19,
      imageUrl: 'https://i.ibb.co/8PhwVYZ/corn-cobs.png',
      category: 'Grains',
      isOnSale: false,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Peas',
      name: 'Peas',
      price: 0.99,
      salePrice: 0.49,
      imageUrl: 'https://i.ibb.co/7GHM7Dp/peas.png',
      category: 'Grains',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    // Herbs
    ProductEntity(
      productId: 'Asparagus',
      name: 'Asparagus',
      price: 6.99,
      salePrice: 4.99,
      imageUrl: 'https://i.ibb.co/RYRvx3W/Asparagus.png',
      category: 'Herbs',
      isOnSale: false,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Brokoli',
      name: 'Brokoli',
      price: 0.99,
      salePrice: 0.89,
      imageUrl: 'https://i.ibb.co/KXTtrYB/Brokoli.png',
      category: 'Herbs',
      isOnSale: true,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Buk-choy',
      name: 'Buk-choy',
      price: 1.99,
      salePrice: 0.99,
      imageUrl: 'https://i.ibb.co/MNDxNnm/Buk-choy.png',
      category: 'Herbs',
      isOnSale: true,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Chinese-cabbage-wombok',
      name: 'Chinese-cabbage-wombok',
      price: 0.99,
      salePrice: 0.5,
      imageUrl: 'https://i.ibb.co/7yzjHVy/Chinese-cabbage-wombok.png',
      category: 'Herbs',
      isOnSale: false,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Kangkong',
      name: 'Kangkong',
      price: 0.99,
      salePrice: 0.5,
      imageUrl: 'https://i.ibb.co/HDSrR2Y/Kangkong.png',
      category: 'Herbs',
      isOnSale: false,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Leek',
      name: 'Leek',
      price: 0.99,
      salePrice: 0.5,
      imageUrl: 'https://i.ibb.co/Pwhqkh6/Leek.png',
      category: 'Herbs',
      isOnSale: false,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Spinach',
      name: 'Spinach',
      price: 0.89,
      salePrice: 0.59,
      imageUrl: 'https://i.ibb.co/bbjvgcD/Spinach.png',
      category: 'Herbs',
      isOnSale: true,
      isPiece: true,
      quantity: '',
      description: '',
      reviews: [],
    ),
    ProductEntity(
      productId: 'Almond',
      name: 'Almond',
      price: 8.99,
      salePrice: 6.5,
      imageUrl: 'https://i.ibb.co/c8QtSr2/almand.jpg',
      category: 'Nuts',
      isOnSale: true,
      isPiece: false,
      quantity: '',
      description: '',
      reviews: [],
    ),
  ];
}
